### ISSUE TITLE
this work has been folded into the official emacs repo?

### ISSUE THREAD

**Issue by mcarifio** [fejfighter/emacs#3]
Based on my reading of the traffic at https://lists.gnu.org/archive/html/emacs-devel/2020-11/msg00697.html, has the work in this repo been merged into the savannah repo?  I'm trying to build from source on Ubuntu 20.10. I can get emacs to compile and run, but I'm not sure if I'm running the gtk wayland version. Is there an elisp expression that will tell me? Please advise. Ty.

**Comment by fejfighter** [comment]
Hi @mcarifio 

yes this repository has been pushed to savannah under the feature/pgtk branch, there have been a few updates there since I last updated my branches here.

the easiest way to confirm is to call the function `(pgtk-backend-display-class)`

it should respond with "GDKWaylandDisplay", if it's on X it will respond with "GDKX11Display"

if it's not defined could you reply with the value of the variable:  `system-configuration-options`

**Comment by mcarifio** [comment]
`feature/pgtk` hasn't yet been merged into `master`. I was building the wrong branch. Once I checked out the right branch (and fixed a little shell script to drive the configure), I got the pgtk version. The function above was enormously helpful to guide me, ty.

**Comment by fejfighter** [comment]
ahh, yeah.

unfortunately we are a little off getting into master, even with experimental status. 

Please post any other issues you get on that branch in the gnu bug tracker or emacs-devel

Thanks for testing

**Comment by mcarifio** [comment]
I should be thanking you and Yuuki Harano for this work. I'm trying to adopt Wayland and it's apps. NVidia often blocks me and XWayland continues to confuse me. You might want to add a paragraph in the README.md file that this repo is for issues and history. Or something like that.
